services:
  app:
    build:
      args:
        user: financialPortfolioApiBackend
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: php:8.4-fpm
    container_name: financialPortfolioApiBackend-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - financialPortfolioApiBackend

  nginx:
    image: nginx:alpine
    container_name: financialPortfolioApiBackend-nginx
    restart: unless-stopped
    ports:
      - 8000:80
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d/
    networks:
      - financialPortfolioApiBackend

networks:
  financialPortfolioApiBackend:
    driver: bridge
